@startuml packages_pushshift_python
set namespaceSeparator none
top to bottom direction
skinparam componentStyle rectangle
rectangle "_pushshift_api\n1 python file" as _pushshift_api
rectangle "_pushshift_community\n1 python file" as _pushshift_community
rectangle "_pushshift_file_handler\n1 python file" as _pushshift_file_handler
rectangle "_pushshift_modeling\n1 python file" as _pushshift_modeling
rectangle "_pushshift_queries\n1 python file" as _pushshift_queries
rectangle "_pushshift_scalers\n1 python file" as _pushshift_scalers
rectangle "_pushshift_subreddits\n1 python file" as _pushshift_subreddits
rectangle "conftest\n1 python file" as conftest
rectangle "pushshift_python\n1 python file" as pushshift_python
_pushshift_community --> _pushshift_scalers
_pushshift_queries --> _pushshift_scalers
_pushshift_subreddits --> _pushshift_api
pushshift_python --> _pushshift_api
pushshift_python --> _pushshift_community
pushshift_python --> _pushshift_file_handler
pushshift_python --> _pushshift_modeling
pushshift_python --> _pushshift_queries
pushshift_python --> _pushshift_scalers
pushshift_python --> _pushshift_subreddits
@enduml
