@startuml
title pushshift_python Tooling Integrations
left to right direction
skinparam shadowing false
skinparam defaultFontName Monospace
skinparam componentStyle rectangle
skinparam linetype ortho
rectangle ".github/workflows/ci.yml\n9 detected tools" as source_github_workflows_ci_yml #E0F2FE
rectangle "Great_Lakes_HPC/maintenance/back_it_all_up.sh\n5 detected tools" as source_great_lakes_hpc_maintenance_back_it_all_up_sh #E0F2FE
rectangle "Great_Lakes_HPC/maintenance/backup_csvz_to_turbo.sh\n5 detected tools" as source_great_lakes_hpc_maintenance_backup_csvz_to_turbo_sh #E0F2FE
rectangle "Great_Lakes_HPC/maintenance/backup_labelz_from_scratch.sh\n4 detected tools" as source_great_lakes_hpc_maintenance_backup_labelz_from_scratch_sh #E0F2FE
rectangle "Great_Lakes_HPC/maintenance/backup_metricz_from_scratch.sh\n4 detected tools" as source_great_lakes_hpc_maintenance_backup_metricz_from_scratch_sh #E0F2FE
rectangle "Great_Lakes_HPC/maintenance/backup_networkz_from_scratch.sh\n4 detected tools" as source_great_lakes_hpc_maintenance_backup_networkz_from_scratch_sh #E0F2FE
rectangle "Great_Lakes_HPC/maintenance/backup_quarterly_metricz_from_scratch.sh\n4 detected tools" as source_great_lakes_hpc_maintenance_backup_quarterly_metricz_from_scratch_sh #E0F2FE
rectangle "Great_Lakes_HPC/maintenance/csv_to_tarball.sh\n3 detected tools" as source_great_lakes_hpc_maintenance_csv_to_tarball_sh #E0F2FE
rectangle "Great_Lakes_HPC/maintenance/insurrection/backup_idlz_to_turbo.sh\n4 detected tools" as source_great_lakes_hpc_maintenance_insurrection_backup_idlz_to_turbo_sh #E0F2FE
rectangle "Great_Lakes_HPC/maintenance/tarball_to_csv.sh\n3 detected tools" as source_great_lakes_hpc_maintenance_tarball_to_csv_sh #E0F2FE
rectangle "Great_Lakes_HPC/maintenance/transfer_csvz_to_scratch.sh\n5 detected tools" as source_great_lakes_hpc_maintenance_transfer_csvz_to_scratch_sh #E0F2FE
rectangle "Great_Lakes_HPC/maintenance/transfer_push_file_to_scratch.sh\n5 detected tools" as source_great_lakes_hpc_maintenance_transfer_push_file_to_scratch_sh #E0F2FE
rectangle "Great_Lakes_HPC/sbats/insurrection/GraphD.sbat\n4 detected tools" as source_great_lakes_hpc_sbats_insurrection_graphd_sbat #E0F2FE
rectangle "Great_Lakes_HPC/sbats/insurrection/extract_communities.sbat\n4 detected tools" as source_great_lakes_hpc_sbats_insurrection_extract_communities_sbat #E0F2FE
rectangle "Great_Lakes_HPC/sbats/insurrection/extract_edges.sbat\n4 detected tools" as source_great_lakes_hpc_sbats_insurrection_extract_edges_sbat #E0F2FE
rectangle "Great_Lakes_HPC/sbats/insurrection/extract_insurrection.sbat\n5 detected tools" as source_great_lakes_hpc_sbats_insurrection_extract_insurrection_sbat #E0F2FE
rectangle "Great_Lakes_HPC/sbats/insurrection/map_communities.sbat\n4 detected tools" as source_great_lakes_hpc_sbats_insurrection_map_communities_sbat #E0F2FE
rectangle "Great_Lakes_HPC/sbats/insurrection/map_communities_util.sbat\n4 detected tools" as source_great_lakes_hpc_sbats_insurrection_map_communities_util_sbat #E0F2FE
rectangle "Great_Lakes_HPC/sbats/insurrection/pair_ids.sbat\n5 detected tools" as source_great_lakes_hpc_sbats_insurrection_pair_ids_sbat #E0F2FE
rectangle "Great_Lakes_HPC/sbats/insurrection/reciprocity.sbat\n4 detected tools" as source_great_lakes_hpc_sbats_insurrection_reciprocity_sbat #E0F2FE
rectangle "Great_Lakes_HPC/sbats/label_maker.sbat\n4 detected tools" as source_great_lakes_hpc_sbats_label_maker_sbat #E0F2FE
rectangle "Great_Lakes_HPC/sbats/metric_maker.sbat\n5 detected tools" as source_great_lakes_hpc_sbats_metric_maker_sbat #E0F2FE
rectangle "Great_Lakes_HPC/sbats/network_maker.sbat\n5 detected tools" as source_great_lakes_hpc_sbats_network_maker_sbat #E0F2FE
rectangle "Great_Lakes_HPC/sbats/quarterly_metric_maker.sbat\n5 detected tools" as source_great_lakes_hpc_sbats_quarterly_metric_maker_sbat #E0F2FE
rectangle "Great_Lakes_HPC/sbats/sbatch_preambles.txt\n0 detected tools" as source_great_lakes_hpc_sbats_sbatch_preambles_txt #E0F2FE
cloud "actions/checkout" as tool_actions_checkout #FEF3C7
cloud "actions/setup-python" as tool_actions_setup_python #FEF3C7
cloud "backup_idlz_to_turbo.sh" as tool_backup_idlz_to_turbo_sh #FEF3C7
cloud "backup_labelz_from_scratch.sh" as tool_backup_labelz_from_scratch_sh #FEF3C7
cloud "backup_metricz_from_scratch.sh" as tool_backup_metricz_from_scratch_sh #FEF3C7
cloud "backup_networkz_from_scratch.sh" as tool_backup_networkz_from_scratch_sh #FEF3C7
cloud "backup_quarterly_metricz_from_scratch.sh" as tool_backup_quarterly_metricz_from_scratch_sh #FEF3C7
cloud "black" as tool_black #FEF3C7
cloud "cp" as tool_cp #FEF3C7
cloud "let" as tool_let #FEF3C7
cloud "ls-files" as tool_ls_files #FEF3C7
cloud "mkdir" as tool_mkdir #FEF3C7
cloud "module" as tool_module #FEF3C7
cloud "pip" as tool_pip #FEF3C7
cloud "pylint" as tool_pylint #FEF3C7
cloud "pytest" as tool_pytest #FEF3C7
cloud "python" as tool_python #FEF3C7
cloud "rm" as tool_rm #FEF3C7
cloud "ruff" as tool_ruff #FEF3C7
cloud "tar" as tool_tar #FEF3C7
cloud "tee" as tool_tee #FEF3C7
cloud "wc" as tool_wc #FEF3C7
cloud "which" as tool_which #FEF3C7
source_github_workflows_ci_yml --> tool_actions_checkout
source_github_workflows_ci_yml --> tool_actions_setup_python
source_github_workflows_ci_yml --> tool_black
source_github_workflows_ci_yml --> tool_ls_files
source_github_workflows_ci_yml --> tool_pip
source_github_workflows_ci_yml --> tool_pylint
source_github_workflows_ci_yml --> tool_pytest
source_github_workflows_ci_yml --> tool_ruff
source_github_workflows_ci_yml --> tool_tee
source_great_lakes_hpc_maintenance_back_it_all_up_sh --> tool_cp
source_great_lakes_hpc_maintenance_back_it_all_up_sh --> tool_let
source_great_lakes_hpc_maintenance_back_it_all_up_sh --> tool_mkdir
source_great_lakes_hpc_maintenance_back_it_all_up_sh --> tool_rm
source_great_lakes_hpc_maintenance_back_it_all_up_sh --> tool_wc
source_great_lakes_hpc_maintenance_backup_csvz_to_turbo_sh --> tool_cp
source_great_lakes_hpc_maintenance_backup_csvz_to_turbo_sh --> tool_let
source_great_lakes_hpc_maintenance_backup_csvz_to_turbo_sh --> tool_mkdir
source_great_lakes_hpc_maintenance_backup_csvz_to_turbo_sh --> tool_rm
source_great_lakes_hpc_maintenance_backup_csvz_to_turbo_sh --> tool_wc
source_great_lakes_hpc_maintenance_backup_labelz_from_scratch_sh --> tool_cp
source_great_lakes_hpc_maintenance_backup_labelz_from_scratch_sh --> tool_mkdir
source_great_lakes_hpc_maintenance_backup_labelz_from_scratch_sh --> tool_rm
source_great_lakes_hpc_maintenance_backup_labelz_from_scratch_sh --> tool_wc
source_great_lakes_hpc_maintenance_backup_metricz_from_scratch_sh --> tool_cp
source_great_lakes_hpc_maintenance_backup_metricz_from_scratch_sh --> tool_mkdir
source_great_lakes_hpc_maintenance_backup_metricz_from_scratch_sh --> tool_rm
source_great_lakes_hpc_maintenance_backup_metricz_from_scratch_sh --> tool_wc
source_great_lakes_hpc_maintenance_backup_networkz_from_scratch_sh --> tool_cp
source_great_lakes_hpc_maintenance_backup_networkz_from_scratch_sh --> tool_mkdir
source_great_lakes_hpc_maintenance_backup_networkz_from_scratch_sh --> tool_rm
source_great_lakes_hpc_maintenance_backup_networkz_from_scratch_sh --> tool_wc
source_great_lakes_hpc_maintenance_backup_quarterly_metricz_from_scratch_sh --> tool_cp
source_great_lakes_hpc_maintenance_backup_quarterly_metricz_from_scratch_sh --> tool_mkdir
source_great_lakes_hpc_maintenance_backup_quarterly_metricz_from_scratch_sh --> tool_rm
source_great_lakes_hpc_maintenance_backup_quarterly_metricz_from_scratch_sh --> tool_wc
source_great_lakes_hpc_maintenance_csv_to_tarball_sh --> tool_let
source_great_lakes_hpc_maintenance_csv_to_tarball_sh --> tool_tar
source_great_lakes_hpc_maintenance_csv_to_tarball_sh --> tool_wc
source_great_lakes_hpc_maintenance_insurrection_backup_idlz_to_turbo_sh --> tool_cp
source_great_lakes_hpc_maintenance_insurrection_backup_idlz_to_turbo_sh --> tool_mkdir
source_great_lakes_hpc_maintenance_insurrection_backup_idlz_to_turbo_sh --> tool_rm
source_great_lakes_hpc_maintenance_insurrection_backup_idlz_to_turbo_sh --> tool_wc
source_great_lakes_hpc_maintenance_tarball_to_csv_sh --> tool_let
source_great_lakes_hpc_maintenance_tarball_to_csv_sh --> tool_tar
source_great_lakes_hpc_maintenance_tarball_to_csv_sh --> tool_wc
source_great_lakes_hpc_maintenance_transfer_csvz_to_scratch_sh --> tool_cp
source_great_lakes_hpc_maintenance_transfer_csvz_to_scratch_sh --> tool_let
source_great_lakes_hpc_maintenance_transfer_csvz_to_scratch_sh --> tool_mkdir
source_great_lakes_hpc_maintenance_transfer_csvz_to_scratch_sh --> tool_rm
source_great_lakes_hpc_maintenance_transfer_csvz_to_scratch_sh --> tool_wc
source_great_lakes_hpc_maintenance_transfer_push_file_to_scratch_sh --> tool_cp
source_great_lakes_hpc_maintenance_transfer_push_file_to_scratch_sh --> tool_let
source_great_lakes_hpc_maintenance_transfer_push_file_to_scratch_sh --> tool_mkdir
source_great_lakes_hpc_maintenance_transfer_push_file_to_scratch_sh --> tool_rm
source_great_lakes_hpc_maintenance_transfer_push_file_to_scratch_sh --> tool_wc
source_great_lakes_hpc_sbats_insurrection_graphd_sbat --> tool_module
source_great_lakes_hpc_sbats_insurrection_graphd_sbat --> tool_pip
source_great_lakes_hpc_sbats_insurrection_graphd_sbat --> tool_python
source_great_lakes_hpc_sbats_insurrection_graphd_sbat --> tool_which
source_great_lakes_hpc_sbats_insurrection_extract_communities_sbat --> tool_module
source_great_lakes_hpc_sbats_insurrection_extract_communities_sbat --> tool_pip
source_great_lakes_hpc_sbats_insurrection_extract_communities_sbat --> tool_python
source_great_lakes_hpc_sbats_insurrection_extract_communities_sbat --> tool_which
source_great_lakes_hpc_sbats_insurrection_extract_edges_sbat --> tool_module
source_great_lakes_hpc_sbats_insurrection_extract_edges_sbat --> tool_pip
source_great_lakes_hpc_sbats_insurrection_extract_edges_sbat --> tool_python
source_great_lakes_hpc_sbats_insurrection_extract_edges_sbat --> tool_which
source_great_lakes_hpc_sbats_insurrection_extract_insurrection_sbat --> tool_backup_idlz_to_turbo_sh
source_great_lakes_hpc_sbats_insurrection_extract_insurrection_sbat --> tool_module
source_great_lakes_hpc_sbats_insurrection_extract_insurrection_sbat --> tool_pip
source_great_lakes_hpc_sbats_insurrection_extract_insurrection_sbat --> tool_python
source_great_lakes_hpc_sbats_insurrection_extract_insurrection_sbat --> tool_which
source_great_lakes_hpc_sbats_insurrection_map_communities_sbat --> tool_module
source_great_lakes_hpc_sbats_insurrection_map_communities_sbat --> tool_pip
source_great_lakes_hpc_sbats_insurrection_map_communities_sbat --> tool_python
source_great_lakes_hpc_sbats_insurrection_map_communities_sbat --> tool_which
source_great_lakes_hpc_sbats_insurrection_map_communities_util_sbat --> tool_module
source_great_lakes_hpc_sbats_insurrection_map_communities_util_sbat --> tool_pip
source_great_lakes_hpc_sbats_insurrection_map_communities_util_sbat --> tool_python
source_great_lakes_hpc_sbats_insurrection_map_communities_util_sbat --> tool_which
source_great_lakes_hpc_sbats_insurrection_pair_ids_sbat --> tool_backup_idlz_to_turbo_sh
source_great_lakes_hpc_sbats_insurrection_pair_ids_sbat --> tool_module
source_great_lakes_hpc_sbats_insurrection_pair_ids_sbat --> tool_pip
source_great_lakes_hpc_sbats_insurrection_pair_ids_sbat --> tool_python
source_great_lakes_hpc_sbats_insurrection_pair_ids_sbat --> tool_which
source_great_lakes_hpc_sbats_insurrection_reciprocity_sbat --> tool_module
source_great_lakes_hpc_sbats_insurrection_reciprocity_sbat --> tool_pip
source_great_lakes_hpc_sbats_insurrection_reciprocity_sbat --> tool_python
source_great_lakes_hpc_sbats_insurrection_reciprocity_sbat --> tool_which
source_great_lakes_hpc_sbats_label_maker_sbat --> tool_backup_labelz_from_scratch_sh
source_great_lakes_hpc_sbats_label_maker_sbat --> tool_module
source_great_lakes_hpc_sbats_label_maker_sbat --> tool_python
source_great_lakes_hpc_sbats_label_maker_sbat --> tool_which
source_great_lakes_hpc_sbats_metric_maker_sbat --> tool_backup_metricz_from_scratch_sh
source_great_lakes_hpc_sbats_metric_maker_sbat --> tool_module
source_great_lakes_hpc_sbats_metric_maker_sbat --> tool_pip
source_great_lakes_hpc_sbats_metric_maker_sbat --> tool_python
source_great_lakes_hpc_sbats_metric_maker_sbat --> tool_which
source_great_lakes_hpc_sbats_network_maker_sbat --> tool_backup_networkz_from_scratch_sh
source_great_lakes_hpc_sbats_network_maker_sbat --> tool_module
source_great_lakes_hpc_sbats_network_maker_sbat --> tool_pip
source_great_lakes_hpc_sbats_network_maker_sbat --> tool_python
source_great_lakes_hpc_sbats_network_maker_sbat --> tool_which
source_great_lakes_hpc_sbats_quarterly_metric_maker_sbat --> tool_backup_quarterly_metricz_from_scratch_sh
source_great_lakes_hpc_sbats_quarterly_metric_maker_sbat --> tool_module
source_great_lakes_hpc_sbats_quarterly_metric_maker_sbat --> tool_pip
source_great_lakes_hpc_sbats_quarterly_metric_maker_sbat --> tool_python
source_great_lakes_hpc_sbats_quarterly_metric_maker_sbat --> tool_which
note as toolingGraphSummary
Scanned 25 tooling entrypoints.
Detected 23 third-party tools.
end note
@enduml
